---
-   hosts: all
    gather_facts: False
    tasks:
#      - REMOVE  the LogAn agent to the below host
      - name: copy script for Log analytics Agent
        copy:
         src: /home/oracle/terraform-excercises/oci-certification/logging-analytics/config/agent_config.sh
         dest: /home/opc/agent_config.sh
         directory_mode: no
         owner: opc
         group: opc
         mode: "u+rwx"
        tags:
          - linux
        become: true
        become_user: opc         
#      execute conf script agent ...        
      - name: execute script configure Log analytics Agent      
        command: sh   /home/opc/agent_config.sh REMOVE
        register: logan
        tags:
         - linux
        become: true
        become_user: opc        
#        become_user: root
#        become_method: sudo
        ignore_errors: yes
      - debug: var=logan.stdout_lines